### ISSUE TITLE
Build broke ffmpeg

### ISSUE THREAD

**Issue by thanpolas** [HYPERHYPER/heroku-buildpack-ffmpeg#2]
Hello there,

at some point during the past month the builds started breaking on heroku, ffmpeg exited with error 127 or 9 constantly.

I switched to shunjikonishi/heroku-buildpack-ffmpeg and all got resolved, just wanted to let you know.

**Comment by nrj** [comment]
The tarball was recently updated for use Cedar-14, I assume you're still on Cedar?
